### ISSUE TITLE
Longtap Not working when scroll the view in IOS5

### ISSUE THREAD

**Issue by 3kanth** [sylverb/CIALBrowser#1]
Hi All,

I am using your code in my project,its working for ios4.3 and in ios5.0  not working longtap event in ios5 .
please provide the solution for i,t

**Comment by sylverb** [comment]
Could you try to make this modification ?

in - (void)longPressRecognized:(UILongPressGestureRecognizer *)gestureRecognizer,
change

```
    // convert point from view to HTML coordinate system
    CGPoint offset = [webView scrollOffset];
    CGSize viewSize = [webView frame].size;
    CGSize windowSize = [webView windowSize];

    CGFloat f = windowSize.width / viewSize.width;
    point.x = point.x * f + offset.x;
    point.y = point.y * f + offset.y;
```

to

```
    // convert point from view to HTML coordinate system
    CGSize viewSize = [webView frame].size;
    CGSize windowSize = [webView windowSize];

    CGFloat f = windowSize.width / viewSize.width;
    if ([[[UIDevice currentDevice] systemVersion] doubleValue] >= 5.) {
         pt.x = pt.x * f;
         pt.y = pt.y * f;
    } else {
        // On iOS 4 and previous, document.elementFromPoint is not taking
        // offset into account, we have to handle it
        CGPoint offset = [webView scrollOffset];
        pt.x = pt.x * f + offset.x;
        pt.y = pt.y * f + offset.y;
    }
```

**Comment by 3kanth** [comment]
Oh I am very thanking you sir,

But in some situation ,i.e when scrolling the view scroll up and scroll
down,then long tap on the link it will not work ,

Please explain solution for this small bug also
Thanks
Sreekanth

On Wed, Feb 15, 2012 at 7:58 PM, Sylver Bruneau <
reply@reply.github.com

> wrote:
> 
> Could you try to make this modification ?
> 
> in - (void)longPressRecognized:(UILongPressGestureRecognizer
> *)gestureRecognizer,
> change
> 
> ```
>    // convert point from view to HTML coordinate system
>    CGPoint offset = [webView scrollOffset];
>    CGSize viewSize = [webView frame].size;
>    CGSize windowSize = [webView windowSize];
> 
>    CGFloat f = windowSize.width / viewSize.width;
>    point.x = point.x * f + offset.x;Th
>    point.y = point.y * f + offset.y;
> ```
> 
> to
> 
> ```
>    // convert point from view to HTML coordinate system
>    CGSize viewSize = [webView frame].size;
>    CGSize windowSize = [webView windowSize];
> 
>    CGFloat f = windowSize.width / viewSize.width;
>    if ([[[UIDevice currentDevice] systemVersion] doubleValue] >= 5.) {
>         pt.x = pt.x * f;
>         pt.y = pt.y * f;
>    } else {
>        // On iOS 4 and previous, document.elementFromPoint is not
> ```
> 
> taking
>            // offset into account, we have to handle it
>            CGPoint offset = [webView scrollOffset];
>            pt.x = pt.x \* f + offset.x;
>            pt.y = pt.y \* f + offset.y;
>        }
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sylverb/CIALBrowser/issues/1#issuecomment-3981079

## 

Thanks&Regards
Srikanth.I
Software Engineer-Iphone Developer
9701149593

**Comment by sylverb** [comment]
Please check my latests commits, it should fix this issue !
