### ISSUE TITLE
How to open a link in Newpage ?

### ISSUE THREAD

**Issue by 3kanth** [sylverb/CIALBrowser#2]
Hi I am using CIALBrowser code in my project ,i want to add one thing
to this project ,

I want to open a link in newpage ,please help me 

Thansk
Srikanth

**Comment by sylverb** [comment]
You're right, multiple UIWebView management is not yet implemented in CIALBrowser. What kind of help do you need exactly ?

**Comment by 3kanth** [comment]
thanks,
i want to open a link in New UIWebView i.e When longtap is pressed i added one button name is Open in NewPage
when click on it ,i Want to open that link NewPage(UIWebView)

**Comment by sylverb** [comment]
You'll have to rework the code to be able to manage multiple UIWebView and to implement some ways to switch between UIWebViews, add some new UIWebViews, close UIWebViews ... It's an important amount of work and I didn't find time to work on this yet !
I've found some open source projects that could be useful to handle the multiple windows part (like https://github.com/100grams/HGPageScrollView or https://github.com/hollance/MHTabBarController ). but there is still some work to integrate them in CIALBrowser ...

**Comment by 3kanth** [comment]
Thank you
