### ISSUE TITLE
Could you set a tag version?

### ISSUE THREAD

**Issue by katsuyoshi** [sylverb/CIALBrowser#7]
I want to register CIALBrowser to CocoaPods. 
https://github.com/CocoaPods/CocoaPods/

It's required a tag version for registration.
Could you set a tag version?

**Comment by sylverb** [comment]
v1.0 pushed ;)

**Comment by katsuyoshi** [comment]
Thank you.
I've just added CIALBrowser to CocoaPods / Specs.
https://github.com/CocoaPods/Specs

I think you will understand reading here how to use CocoaPod .
https://github.com/CocoaPods/CocoaPods/

Writing a Podfile.
run 'pod install'.

Then CIALBrowser is included in a Project.
